### ISSUE TITLE
NoTransactionException when rolling back a transaction using @Transactional

### ISSUE THREAD

**Issue by geetrawat** [spring-projects/spring-data-geode#481] opened 2021-02-03 20:01 UTC
Client App is using multiple threads to modify the same object concurrently in the same region (replicated region in this case) with transaction. When the second transaction fails, the transaction rollsback (which is correct). However, in doing so, it is throwing the following exception
```
org.springframework.transaction.NoTransactionException: No transaction is associated with the current thread; are multiple transaction managers present?; nested exception is java.lang.IllegalStateException: Thread does not have an active transaction

at org.springframework.data.gemfire.transaction.GemfireTransactionManager.doRollback(GemfireTransactionManager.java:235)

at org.springframework.transaction.support.AbstractPlatformTransactionManager.doRollbackOnCommitException(AbstractPlatformTransactionManager.java:893)

at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:776)

at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:712)

at org.springframework.transaction.interceptor.TransactionAspectSupport.commitTransactionAfterReturning(TransactionAspectSupport.java:631)

at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:385)

at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:99)

at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)

at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)

at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689)

at <our class>

at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)

at java.util.concurrent.FutureTask.run(FutureTask.java)

at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)

at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

at java.lang.Thread.run(Thread.java:748)

Caused by: java.lang.IllegalStateException: Thread does not have an active transaction

at org.apache.geode.internal.cache.TXManagerImpl.rollback(TXManagerImpl.java:532)

at org.springframework.data.gemfire.transaction.GemfireTransactionManager.doRollback(GemfireTransactionManager.java:232)

... 17 more
```

**Comment by jxblum** [comment] 2021-02-03 20:40
In general, an **_Issue_** (and particularly, a bug report) should follow this format:

1. Bug description / summary
2. Steps to reproduce
3. Expected outcome
4. Actual outcome

Along with supplying any artifacts, including but not limited to: [application] configuration metadata, logs, stack traces, thread dumps, [mock] data, etc.

Ideally, if you there are any tests that can reliably reproduce the issue, those are highly welcomed.

**Comment by jxblum** [comment] 2021-02-03 20:47
Having stated the above...

BUG DESCRITION

I get that the problem is related to 2 (or more) transactions initiated from a client (i.e. GemFire/Geode `ClientCache` instance) to a (cluster of) server(s) with a `REPLICATE` Region, where the first transaction is successful (i.e. commits, ??), however, the 2nd transaction fails and successfully rolls back, but unfortunately results in a `o.s.transaction.NoTransactionException`, which seems to somehow be caused by GemFire/Geode:

```
Caused by: java.lang.IllegalStateException: Thread does not have an active transaction
  at org.apache.geode.internal.cache.TXManagerImpl.rollback(TXManagerImpl.java:532)
```

STEPS TO REPRODUCE:

?

EXPECTED OUTCOME

Rollback; no Exception

ACTUAL OUTCOME:

2nd transaction failed and successfully rolled back, however, the _Spring Transaction Management Infrastructure_ apparently through a `NoTransactionException` during the rollback operation.

This seems to have been caused by GemFire/Geode itself in the call to `org.apache.geode.internal.cache.TXManagerImpl.rollback(TXManagerImpl.java:532)` from the Spring `PlatformTransactionManager` for Apache Geode (i.e. the SDG `GemfireTransactionManager`) ` `org.springframework.data.gemfire.transaction.GemfireTransactionManager.doRollback(GemfireTransactionManager.java:232)`.

**Comment by jxblum** [comment] 2021-02-03 21:27
Care to share:

* Any Maven POM or Gradle build setup/configuration, or
* Alternatively, software versions (OS, SDG, Apache Geode)
* Artifacts (application configuration metadata, logs, stack traces, thread dumps, [mock] data, etc)
* Tests (if possible) reliably reproducing the issue (should be runnable).
* Etc.

Include what is relevant.

??

**Comment by jxblum** [comment] 2021-02-04 17:47
Re-opening to request more feedback.

**Comment by jxblum** [comment] 2021-02-04 18:00
The following (recent addition of the) [test class](https://github.com/spring-projects/spring-data-geode/blob/master/spring-data-geode/src/test/java/org/springframework/data/gemfire/transaction/ConcurrentClientDataAccessTransactionsWithRollbackIntegrationTests.java) to the SDG test suite proves that [_Spring's Transaction Management_ infrastructure](https://docs.spring.io/spring-framework/docs/current/reference/html/data-access.html#transaction) (initiated by the _Spring Framework_ [`@Transactional` annotation](https://docs.spring.io/spring-framework/docs/current/reference/html/data-access.html#transaction-declarative-annotations) ([Javadoc](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/transaction/annotation/Transactional.html))) along with SDG's [`GemfireTransactionManager`](https://docs.spring.io/spring-data/geode/docs/current/reference/html/#apis:transaction-management) ([Javadoc](https://docs.spring.io/spring-data/geode/docs/current/api/org/springframework/data/gemfire/transaction/GemfireTransactionManager.html)) works correctly in the context of concurrent client transactions (initiated from different requests/Threads) against server(s) with a `REPLICATE` _Region_.  In fact, this problem should be largely _Region DataPolicy_ independent.

**Comment by spring-projects-issues** [comment] 2021-02-11 17:52
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment] 2021-02-18 17:52
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-projects-issues** 2021-02-18 17:52 UTC
Labels: in: transactions, status: feedback-reminder, status: invalid, status: waiting-for-feedback
