### ISSUE TITLE
Add new Geode properties: `ssl-client-protocols` and `ssl-server-protocols`

### ISSUE THREAD

**Issue by jdeppe-pivotal** [spring-projects/spring-data-geode#581] opened 2022-03-07 20:44 UTC
These new properties have been added by this change: https://github.com/apache/geode/pull/7315

**Comment by pivotal-jbarrett** [comment] 2022-03-08 15:09
These new properties are required to dig certain versions of members out of a hole dug with `SSLv2Hello` as documented int [GEODE-9991](https://issues.apache.org/jira/browse/GEODE-9991). I will be writing more details on the migration process. There is an `SocketCreatorUpgradeTest` that tests all the scenarios back to Geode 1.8.0. While this settings apply to all SSL protected components they are really only necessary for p2p communications.

**Comment by jxblum** [comment] 2022-03-16 20:23
@jdeppe-pivotal and @pivotal-jbarrett - 

Looks like these new GemFire/Geode properties were added to the codebase on `develop`, implying these new properties will only be part of Apache Geode 1.15?  In which case, this will only apply to the SDG `main-next` branch and officially brought into SDG once SDG is rebased on Apache Geode 1.15.

Will these new properties be added (back ported) to Apache Geode 1.14 or 1.13, do you know?

I suspect since these property additions were prompted by the JDK version, and since both Apache Geode 1.13/1.14 are based on JDK 8 (default), with extended support for JDK 11, then perhaps not.  Although if you increase your JDK version range of support in Apache Geode 1.13/1.14, then maybe?

**Comment by pivotal-jbarrett** [comment] 2022-03-16 20:41
It has yet to be determined if these properties will be back ported to older releases. So far the changes are only in develop (1.16) and haven't been back ported to 1.15 yet either.

**Comment by onichols-pivotal** [comment] 2022-03-29 18:58
Geode support/1.15 branch was annulled and develop is 1.15, so this can be fixed in main-next already (independent of whether we decide to backport or not).  Make sure you are looking at Geode 1.15.0-build.1000 or later build.  The issue is not primarily motivated by JDK9+ work, but rather, by changes between JDK8 patches (e.g. someone upgrading from JDK 1.8.0_242 to 1.8.0_322)

**Comment by jxblum** [comment] 2022-03-29 23:47
This issue can only be resolved in SDG once the properties are added to the Apache Geode branch (e.g. `develop`) representing the next GA version (e.g. `1.15`) after current (i.e. `1.14`).

Technically, from SDG's POV, this means [`1.15` build snapshots](https://github.com/spring-projects/spring-data-geode/blob/main-next/spring-data-geode/pom.xml#L25) that are located [here](https://github.com/spring-projects/spring-data-geode/blob/main-next/pom.xml#L63-L73). Since this only recently changed, it was not actionable until now.

FYI, no other _Spring Data_ (SD) module looks ahead, or builds on the underlying data store build snapshots like _Spring Data for Apache Geode_ (SDG).  No SD module releases any version of the SD module: snapshot, milestone, release candidate, release, or otherwise on a non-released version of the underlying data store. So, this is rather an exception than the rule, and as such, these sort of tickets are not high priority relative to release deliverables. Effectively, what is currently in released versions of Apache Geode is what we build against and support, nothing more.

The only reason `main-next` exists in the first place, building SDG against the latest build snapshots of Apache Geode, is to prepare SDG for what is coming next, otherwise `main-next` is not strictly necessary for SDG development. It is not in our best interest to be chasing development-time activities in Apache Geode, which are subject to change, as this particular issue and the entire Apache Geode `1.15` development/release illustrates, which has been anything but predictable.

At any rate, this issues has been addressed now.

**Closed by jxblum** 2022-03-29 23:47 UTC
Labels: in-progress, status: ideal-for-contribution, status: feedback-provided
